# ex04-Constrain the Number of Rows Returned by a SELECT Query

Often it is not convenient to show all rows on screen as you have to scroll. We can use use SQLite ***LIMIT*** clause to constrain the number of rows returned by a query. This can be used for testing or to prevent consuming excessive resources if the query returns more information than expected.

The following illustrates the syntax of the LIMIT clause:
- SELECT column_list FROM table_name LIMIT row_count;

In [1]:
%load_ext sql

### 1. Connet to the given database of demo.db3

In [2]:
%sql sqlite:///data/demo.db3

u'Connected: @data/demo.db3'

### 2. Retrieving the first 10 rows of the table of watershed_yearly

Add the LIMIT clause to the SELECT statement to get exact 10 rows.

In [4]:
%sql SELECT * From watershed_yearly LIMIT 10

 * sqlite:///data/demo.db3
Done.

[(1981, 895.6051025390625, 130.3574676513672, 51.33439254760742, 406.0739440917969, 443.198486328125, 0.0, 18819.70703125, 236.98300170898438, 840.6874389648438, 609.706787109375, 91.08026123046875, 0.03293686360120773, 0.06417319178581238, 5.615890026092529, 7.339915752410889, 11.857464790344238, 0.008220621384680271, 1.461671233177185, 0.0),
 (1982, 884.670654296875, 92.21265411376953, 50.34769058227539, 367.41070556640625, 424.6783752441406, 0.0, 19425.8359375, 256.79083251953125, 872.07470703125, 530.0245971679688, 64.80978393554688, 0.00797836109995842, 0.04918050765991211, 4.239809036254883, 7.676506042480469, 10.873835563659668, 0.007697358727455139, 1.343782901763916, 0.0),
 (1983, 816.6605224609375, 129.16310119628906, 54.47308349609375, 445.33306884765625, 462.76324462890625, 0.0, 18476.1953125, 237.70555114746094, 797.04736328125, 652.8157958984375, 92.04792785644531, 0.13790887594223022, 0.048595353960990906, 3.882063388824463, 7.301627159118652, 12.202207565307617, 0.015354366973042488, 1.5196093320846558, 0.0),
 (1984, 867.5743408203125, 95.57946014404297, 46.948646545410156, 347.2448425292969, 408.5397033691406, 0.0, 17727.712890625, 223.08975219726562, 911.25634765625, 510.37933349609375, 63.0908203125, 0.01470834668725729, 0.0440557599067688, 5.141480922698975, 6.492110729217529, 10.941608428955078, 0.011575199663639069, 1.3742408752441406, 0.0),
 (1985, 637.7255249023438, 75.55760192871094, 45.336883544921875, 358.2953186035156, 361.4852294921875, 0.0, 15840.5400390625, 236.32135009765625, 990.8557739257812, 499.33990478515625, 49.63069152832031, 0.05470645800232887, 0.046555422246456146, 3.113034963607788, 6.522554874420166, 8.959033966064453, 0.010798747651278973, 1.1150814294815063, 0.0),
 (1986, 733.8412475585938, 65.63016510009766, 36.76259231567383, 241.9388427734375, 281.6683349609375, 0.0, 16059.4345703125, 243.0305633544922, 977.513427734375, 358.09368896484375, 48.7893180847168, 0.0010510582942515612, 0.040558818727731705, 2.8865158557891846, 6.505890369415283, 7.870068073272705, 0.013286528177559376, 0.970182478427887, 0.0),
 (1987, 1007.8944702148438, 110.28632354736328, 62.23741912841797, 445.5394592285156, 493.0043029785156, 0.0, 19541.869140625, 256.9570007324219, 841.0055541992188, 641.2118530273438, 76.02854919433594, 0.013590915128588676, 0.05216805264353752, 3.6147713661193848, 5.987320899963379, 14.57848834991455, 0.019578929990530014, 1.8156678676605225, 0.0),
 (1988, 895.8466186523438, 149.65235900878906, 61.493255615234375, 450.4956970214844, 493.1164245605469, 0.0, 17205.849609375, 220.8395233154297, 891.13330078125, 686.12744140625, 101.2978744506836, 0.025784092023968697, 0.04415411874651909, 3.241307258605957, 5.892490386962891, 13.989458084106445, 0.030675839632749557, 1.7415385246276855, 0.0),
 (1989, 930.10546875, 111.37128448486328, 57.6666145324707, 418.1727600097656, 474.9247741699219, 0.0, 17915.3359375, 208.58026123046875, 805.931884765625, 609.6959838867188, 74.79584503173828, 0.016387958079576492, 0.04736720025539398, 3.692014217376709, 5.3133368492126465, 10.229286193847656, 0.025520162656903267, 1.2660586833953857, 0.0),
 (1990, 751.4553833007812, 102.00208282470703, 54.310569763183594, 409.75189208984375, 435.1587829589844, 0.0, 16842.517578125, 213.63233947753906, 966.4890747070312, 589.3450317382812, 73.0428695678711, 0.007093863561749458, 0.04154253378510475, 3.0770206451416016, 5.872688293457031, 9.7684326171875, 0.025202790275216103, 1.2055107355117798, 0.0)]

### Note

Some DBMSs offer non-standard syntax either instead of or in addition to SQL standard syntax. Variants of the simple ***limit*** query for different DBMSes can be found at https://en.wikipedia.org/wiki/Select_(SQL)